permalink: /:categories/:title/
url: "http://annpud.github.io"
full_name: "annpud's blog"
first_name: "annPud"
last_name: ""
blog_title: "annpud"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "mengmengda"
